### ISSUE TITLE
NewResponseWriter appears to leak goroutines

### ISSUE THREAD

**Issue by sajal** [nbari/violetear#14]
https://github.com/nbari/violetear/blob/7450092af2f65a7a183f6d58f353876490c89894/responsewriter.go#L26-L29

https://golang.org/pkg/net/http/#CloseNotifier
```
        // After the Handler has returned, there is no guarantee
        // that the channel receives a value.
```

That's 1 goroutine to leak for each request.
To reproduce. 

1. Start a http server with pprof enabled. 
2. Access any url handled by violetear multiple times.
3. Visit http://localhost:8080/debug/pprof/goroutine?debug=2  (adjust url to your server)
4. Notice the following goroutine , showing up roughly the number of requests made during step 2

```
goroutine 11 [chan receive, 7 minutes]:
github.com/nbari/violetear.NewResponseWriter.func1(0xc420066000, 0xc4245596d0)
	/home/sajal/go/src/github.com/nbari/violetear/responsewriter.go:27 +0x34
created by github.com/nbari/violetear.NewResponseWriter
	/home/sajal/go/src/github.com/nbari/violetear/responsewriter.go:26 +0x153
```

I am not sure what is the purpose of that goroutine, but I think it should be cancelled once the response has been satisfied.

**Comment by nbari** [comment]
Hi, @sajal thanks for checking this, I think that could be better to use per handler and within a context the `notify.CloseNotify()` otherwise I agree that is just a waste to create a goroutine per each request.

**Comment by sajal** [comment]
I think creation of the goroutine is not a big deal, the issue is that the goroutine blocks forever.

```
 go func() { 
    select{
    case <-notify :
 	rw.status = 499 
   case <- rw.done: //done is some channel that signals response has been served.
    }
 }() 
```
^ done could be closed once `ServeHTTP` returns https://github.com/nbari/violetear/blob/72cf83a095fe6dcd7bc4bc16d0aac49696b8c614/violetear.go#L259-L263 

For the time being I simply removed the `CloseNotify` stuff from my copy of violetear,

**Comment by nbari** [comment]
Just did a [small test](https://github.com/nbari/go-sandbox/blob/master/profile-violetear/profile/main.go#L11-L13) with like you suggest with a sleep, and a lot of goroutines are hanging:

    func hello(w http.ResponseWriter, r *http.Request) {
	     time.Sleep(time.Millisecond)
         w.Write([]byte("hello"))
    }

Very interesting, any ideas on how to fix this are more than welcome.

**Comment by nbari** [comment]
I just removed from the `ResponseWriter` and better delegate this to a handler, like you properly point `there is no guarantee that the channel receives a value.` 

Will work later on an example or handler to have the same effect, many thanks again for testing and catching this out 👍

**Comment by sajal** [comment]
FYI just stumbled upon : https://golang.org/src/net/http/httputil/reverseproxy.go?s=2588:2649#L148

I guess thats one way to exit the goroutine upon normal fullfilment of request.

**Comment by nbari** [comment]
Hi @sajal thanks, this seems to be the way to handle it,  will do some tests


From: https://golang.org/src/net/http/httputil/reverseproxy.go?s=2588:2649#L147:

    ctx := req.Context()
  	if cn, ok := rw.(http.CloseNotifier); ok {
  		var cancel context.CancelFunc
  		ctx, cancel = context.WithCancel(ctx)
  		defer cancel()
  		notifyChan := cn.CloseNotify()
  		go func() {
  			select {
  			case <-notifyChan:
  				cancel()
  			case <-ctx.Done():
  			}
  		}()
  	}

**Comment by nbari** [comment]
https://stackoverflow.com/a/44146619/1135424

The context replaces in go >1.8 the CloseNotify in any case I prefer to have it on the handler than in the main router
