### ISSUE TITLE
ResponseWriter Interface to support Hijack() to allow websocket

### ISSUE THREAD

**Issue by JeffMerlet** [nbari/violetear#15]
In order to support websocket with violetear, using something like [Gorilla websocket](https://github.com/gorilla/websocket), violetear's ResponseWriter implementation would need to support the Hijack() function. The Gin project added that feature for the same reason; see https://github.com/gin-gonic/gin/pull/105/commits/4a24c47a69f56e8275ef330beca3c2925d270948

Thanks!

**Comment by nbari** [comment]
Hi, @JeffMerlet to support all interfaces don't use `LogRequests` by default is disabled, or set it to false:
  
     router := violetear.New()
     router.LogRequests = false

Please give a try and let me know if works.

**Comment by JeffMerlet** [comment]
I can confirm that when setting router.LogRequests to `false` I'm able to connect to the websocket without any problem; and was even able to retrieve a named param used on the web socket URL without any problem.

**Comment by JeffMerlet** [comment]
I will close the issue now. But I would suggest to add some documentation and/or simple example about it as it could be helpful for others. Thanks and great job on the router!

**Comment by nbari** [comment]
@JeffMerlet just in case https://violetear.org/post/websocket-hijack/ is not much but hope helps please feel free to modify/chance as convenient.
