### ISSUE TITLE
Get parameters

### ISSUE THREAD

**Issue by gallart** [nbari/violetear#18]
Hi,

How to extract data from POST requests ?

Thanks

**Comment by nbari** [comment]
Hi @gallart here is a small [example](http://play.golang.org/p/aMouI8ReGhi), but may be worth for you to check the net/http docs https://golang.org/pkg/net/http/, **violetear** doesn't modify/changes the r `*http.Request` behavior so :

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/nbari/violetear"
)

func handler(w http.ResponseWriter, r *http.Request) {
	r.ParseForm()
	x := r.Form.Get("foo")
	fmt.Println(x)
}

func main() {
	router := violetear.New()
	router.HandleFunc("*", handler, "POST") // catchall request but only accept  POST method
	log.Fatal(http.ListenAndServe(":8080", router))
}
```

Then from the command line:

    curl -d "foo=bar" -X POST http://localhost:8080
