### ISSUE TITLE
do some benchmarks

### ISSUE THREAD

**Issue by nbari** [nbari/violetear#3]
Router currently implementing a trie, but when specifying methods per request uses a map.

```
router.HandleFunc("/test_get", handleView, "GET, HEAD")
router.HandleFunc("/test_post", handleView, "POST")
```

Besides that router supports dynamic routing, but for this uses regex 

```
router.AddRegex(":ip", `^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$`)
router.HandleFunc("/command/ping/:ip", ip_handler, "GET")
```

Router working fine and in theory "fast" but nothing better than doing some benchmarks.

**Comment by leonardogcsoares** [comment]
Will try to tackle this for you! Will be an interesting experience! =D

**Comment by nbari** [comment]
That would be great, thanks.

**Comment by nbari** [comment]
For now, this works https://github.com/smallnest/go-web-framework-benchmark
